export enum ReportType {
  PREPROCESSED = 'PREPROCESSED',
  IMMEDIATE = 'IMMEDIATE',
}

export enum ReportCode {
  MONTHLY_TREND = 'MONTHLY_TREND',
  YEARLY_TREND = 'YEARLY_TREND',
  DAILY_INCOME = 'DAILY_INCOME',
  DAILY_OUTCOME = 'DAILY_OUTCOME',
  TOP_CLIENTS = 'TOP_CLIENTS',
  CLIENT_COUNT = 'CLIENT_COUNT',
  WALLET_COUNT = 'WALLET_COUNT',
  LOAN_COUNT = 'LOAN_COUNT',
  MONTHLY_INTERESTS = 'MONTHLY_INTERESTS',
  LATEST_TRANSACTIONS = 'LATEST_TRANSACTIONS',
  TOP_TRANSACTIONS = 'TOP_TRANSACTIONS',
  LATEST_INVOICES = 'LATEST_INVOICES',
}